[theme]
base = "light"
primaryColor = "#B5835A"
backgroundColor = "#F6F9F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = false
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"


